### ISSUE TITLE
Invalid build order in FutureGatewayFramework/fgSetup

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgSetup#6]
1. Please enable adding issues to this fork as described [here](https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork).
2. When installing `APIServerDaemon` the build order is invalid. In [lines (212-220)](https://github.com/FutureGatewayFramework/fgSetup/blob/master/APIServerDaemon/setup_apt-get.sh#L212-L220) the script reads files which are only created in [lines 298-308](https://github.com/FutureGatewayFramework/fgSetup/blob/master/APIServerDaemon/setup_apt-get.sh#L298-L308). Without manual intervention, it is impossible to build FG right now.

**Comment by ricsxn** [comment]
Tests done on top of already existing files allowed to generate this error.
This has been fixed in commit:
https://github.com/FutureGatewayFramework/fgSetup/commit/2f7c0ccfe68e242ecf3f6dc5f45deae004aa2d20
